version: "3.8"

services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=pifinity1
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqlDb
    image: fedincib/pifinity:0.0.3
    restart: on-failure
    ports:
      - 8084:8084
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqlDb:3306/pifinity1?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: